name: wedfluencer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  shared_preferences: null
  image_picker: ^0.8.5+3
  flutter_image_compress: ^1.1.1
  page_transition: ^2.0.9
  overlay_support: ^2.1.0
  #  audio_waveforms: ^1.0.4
  lottie: ^2.6.0
  #  flutter_card_swiper: ^6.0.0
  #  assets_audio_player: ^3.1.1
  #  flutter_sound: ^9.2.13
  responsive_framework: ^1.1.1
  auto_size_text: ^3.0.0
  flutter_localization: ^0.1.14
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  sleek_circular_slider: ^2.0.1
  animated_notch_bottom_bar: ^1.0.0
  syncfusion_flutter_charts: ^22.1.34
  awesome_snackbar_content: ^0.1.3
  syncfusion_flutter_datepicker:
  day_night_time_picker: ^1.3.0+1
  qr_code_scanner: ^1.0.1
  dropdown_button2: ^2.3.9
  flutter_otp_text_field: ^1.1.1
  intl_phone_number_input: ^0.7.4
  google_places_flutter: ^2.0.8
  multi_dropdown: ^2.1.4
  video_player: ^2.8.3
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/logos/