
default_platform(:ios)

platform :ios do


  def generate_api_key
    app_store_connect_api_key(
        key_id: "CW93X73YU2",
        issuer_id: "a8b6d074-e009-4d23-b627-a4969e864ccb",
        key_filepath: "./AuthKey_CW93X73YU2.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
     )
  end

  def common_build_actions

#     setup_ci(force: true)
#     setup_circle_ci

    create_keychain(
      name: "tempKeychain",
      password: "2762",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
    )

#     sync_code_signing(
#       type: "appstore",
#       readonly: is_ci
#     )

    update_code_signing_settings(
      use_automatic_signing: false,
    )
    unlock_keychain(
        path: "/Users/runner/Library/Keychains/tempKeychain",
        password: "2762"
    )

    match(
        type: "appstore",
        readonly: is_ci,
        keychain_name: 'tempKeychain',
        keychain_password: '2762',
    )

    api_key = generate_api_key

    curr_build_number = app_store_build_number(
      live: false,
      api_key: api_key,
      app_identifier: "com.wedfluencer.app",
      username: "ha@wedfluencer.com"
    )

    increment_build_number(
      build_number: curr_build_number + 1,
    )

    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
#       export_method: "development",
      export_method: "app-store",
      export_options: {
        "tree_shake_icons": false,
        provisioningProfiles: {
            "com.wedfluencer.app" => "match AppStore com.wedfluencer.app"
          }
      }
    )
  end

  lane :deployToTestFlight do
    common_build_actions
    api_key = generate_api_key
    upload_to_testflight(api_key: api_key,)
  end
end