default_platform(:ios)

platform :ios do
  desc "Uploading app on TestFlight"
  lane :releaseToTestflight do
    setup_ci if ENV['CI']
    api_key = app_store_connect_api_key(
      key_id: "CW93X73YU2",
      issuer_id: "a8b6d074-e009-4d23-b627-a4969e864ccb",
      key_filepath: "./AuthKey_CW93X73YU2.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    curr_build_number = app_store_build_number(
          live: false,
          api_key: api_key,
          app_identifier: "com.wedfluencer.app",
          username: "ha@wedfluencer.com"
    )

    increment_build_number(
        build_number: curr_build_number + 1,
    )
    enable_automatic_code_signing

    automatic_code_signing(
      use_automatic_signing: true
    )

    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
         "tree_shake_icons": false,
      }
    )
    pilot(api_key: api_key)
  end
end
