name: build-ios-app
on:
  push:
    branches:
      - 'apis_integration'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: "2.6.10"

#      - run: sudo gem install fastlane
      - name: moving to ios directory
        run: cd ios

      - run: fastlane releaseToTestflight
#        env:
#          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}