name: build-ios-app

on:
  push:
    branches:
      - 'apis_integration'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.6"

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Build and deploy to TestFlight
        working-directory: ./ios
        run: fastlane releaseToTestflight
